services:
  - type: static
    name: beehive-cleaning-services
    region: oregon # You can change this if needed
    buildCommand: vite build
    publishDirectory: dist
    # Rewrite all requests to index.html for client-side routing
    rewrites:
      - source: /*
        destination: /index.html
    # Add custom headers to allow 'unsafe-eval' for scripts
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "script-src 'self' 'unsafe-eval' https:; object-src 'none'; base-uri 'self';"
