services:
  - type: static
    name: beehive-cleaning-services
    region: oregon # You can change this if needed
    buildCommand: vite build
    publishDirectory: dist
    # Rewrite all requests to index.html for client-side routing
    rewrites:
      - source: /*
        destination: /index.html
