services:
  - type: web
    name: beehive-cleaning-services
    env: node
    region: oregon
    buildCommand: vite build
    startCommand: npm start
    nodeVersion: 20
    routes:
      - source: /*
        destination: /index.html
